### ISSUE TITLE
request for more details on backing up etcd

### ISSUE THREAD

**Issue by dbyron0** [trondhindenes/trondsworking-blog-gatsby#1]
Thanks so much for writing https://github.com/trondhindenes/trondsworking-blog-gatsby/blob/master/content/blog/2019-08-09-Kops-Restore/index.md.  It's super helpful.

There's one piece I need yet more help on though -- backing up etcd in the first place.  I'm still using legacy / pre etcd-manager, and have seen [this advice](https://github.com/kubernetes/kops/blob/master/docs/etcd/backup-restore.md#volume-backups-legacy-etcd) which points [here](https://serverlesscode.com/post/lambda-schedule-ebs-snapshot-backups/) but also says:
> Note: this is one of many examples on how to do scheduled snapshots.

Your blog post says:
> It is assumed that you run kops on AWS, and that the "kops state store" s3 bucket has at least one good backup you can use to restore.

but I'm curious how you're actually making backups of etcd.

Thanks again for your help.

**Comment by trondhindenes** [comment]
Ah, that's a good point. So, etcd-manager will auto-create snapshots. I'm not sure of the interval, but at least once per day a new snapshot is created. I also think a snapshot is created after cluster creation (like an initial backup). 
In any case, very good point. I'll clarify the blog post.

**Comment by trondhindenes** [comment]
Fixed by #3

**Comment by dbyron0** [comment]
That's certainly helpful, thank you.  For me in pre-etcd-manager-land, I'm still a little stuck.  Isn't the idea that I'm supposed to have some backup before I give etcd-manager the reins?

**Comment by trondhindenes** [comment]
I'm afraid I can't answer you. We just started using kops, so we don't have any pre-etcd-manager stuff at all. Sorry!

**Comment by dbyron0** [comment]
Aaah well.  I'll keep digging.  Thanks again.
