### ISSUE TITLE
Simplification of etcd restore

### ISSUE THREAD

**Issue by gwkunze** [trondhindenes/trondsworking-blog-gatsby#2]
I read your post https://hindenes.com/2019-08-09-Kops-Restore/ after running into the same issue you ran in to (https://github.com/kopeio/etcd-manager/issues/248). The blogpost was helpful, thank you.

I think you can greatly simplify the restore process you've described, namely, you don't need to run etcd-manager-ctl in your etcd-container, you can run the `list-backups` and `restore-backup` commands outside your cluster, as long as you have access to the state store. You can even do this before bringing your old masters down.

**Comment by trondhindenes** [comment]
Good point @gwkunze . I wanted to keep it in-container to avoid having to document accessing S3 locally (iam keys/profiles etc). But - it at least is worth mentioning that these tools can be run locally if you know what you're doing in terms of aws access.

**Comment by trondhindenes** [comment]
Fixed by #3
